environment:
  JAVA_HOME: C:\Program Files\Java\jdk1.8.0
#

build_script:
  - gradlew assemble --info --warning-mode=all --stacktrace --no-daemon
#

artifacts:
  - path: "luogu/build/libs"
    name: "luogu"
